### ISSUE TITLE
build目录在哪里???

### ISSUE THREAD

**Issue by woopengcheng** [TencentOpen/rapidjson#2]
如题.查看tag的版本也没有.是什么原因呢.是我操作的姿势不对么?求解答.(在readme里提到的在build里面使用premake.但是未找到build.)

**Comment by miloyip** [comment]
build目录是自行建立的。

1. ...
2. Create directory called build in rapidjson source directory.
3. Change to build directory and run cmake .. command to configure your build. Windows users can do the same with cmake-gui application.
4. On Windows, build the solution found in the build directory. On Linux, run make from the build directory.

刚发现中文文档未按英文文档更新，我稍后修正。

**Comment by woopengcheng** [comment]
你回复好快...不亏是腾讯的啊.

**Comment by miloyip** [comment]
已于 ea7b39b960fa1f2baed5d3587dffe1b42f39e3fe 更新 http://miloyip.github.io/rapidjson/zh-cn/ ，谢谢反馈。
